Simplify error output code

diff --git a/colourmail b/colourmail
--- a/colourmail
+++ b/colourmail
@@ -4,10 +4,10 @@ set -eu
 
 # Check necessary commands exist.
 { command -v mime-construct && command -v ansi2txt && command -v ansi2html; } >/dev/null || {
-	echo 'Missing commands' >&2
-	echo 'Need mime-construct, ansi2txt and ansi2html in PATH' >&2
+	echo 'Missing commands'
+	echo 'Need mime-construct, ansi2txt and ansi2html in PATH'
 	exit 1
-}
+} >&2
 
 # Set up an unnamed file descriptor, with a write descriptor to store the
 # input, and two read descriptors for reading to the text and html converters.
