Add test mode
I want calling code to be able to pass in different info depending on
whether colourmail has everything it needs.  Add a test mode to get
colourmail to report that through its exit code.

diff --git a/colourmail b/colourmail
--- a/colourmail
+++ b/colourmail
@@ -2,18 +2,12 @@
 
 set -eu
 
-# Check necessary commands exist.
-{ command -v mime-construct && command -v ansi2txt && command -v ansi2html; } >/dev/null || {
-	echo 'Missing one of mime-construct, ansi2txt or ansi2html' >&2
-	echo 'Falling back to mail' >&2
-	exec mail "$@"
-}
-
 # Implement an interface that means this could be used as a drop-in replacement
 # for the version of `mail` provided by Debian's bsd-mailx package.
 check_empty=
+test_mode=
 header_args=()
-while getopts ':a:b:c:dEfIiNnr:s:u:v' opt; do
+while getopts ':a:b:c:dEfIiNnr:s:tu:v' opt; do
 	case "$opt" in
 		a)	header_args+=(--header "$OPTARG");;
 		b)	header_args+=(--bcc "$OPTARG");;
@@ -21,6 +15,7 @@ while getopts ':a:b:c:dEfIiNnr:s:u:v' opt; do
 		E)	check_empty=YesPlease;;
 		r)	header_args+=(--header "From: $OPTARG");;
 		s)	header_args+=(--subject "$OPTARG");;
+		t)	test_mode=YesPlease;;
 		d|f|I|i|N|n|u|v)
 			printf -- '-%s is not implemented!\n' "$opt" >&2
 			exit 70  # EX_SOFTWARE
@@ -30,6 +25,20 @@ while getopts ':a:b:c:dEfIiNnr:s:u:v' opt; do
 			;;
 	esac
 done
+
+# Check necessary commands exist.  Exit with an error code if we're in test
+# mode (because the caller wants to handle the scenario itself), otherwise exec
+# mail as something that can (hopefully) handle things for us.
+{ command -v mime-construct && command -v ansi2txt && command -v ansi2html; } >/dev/null || {
+	echo 'Missing one of mime-construct, ansi2txt or ansi2html' >&2
+	[[ "$test_mode" ]] && exit 69  # EX_UNAVAILABLE
+	echo 'Falling back to mail' >&2
+	exec mail "$@"
+}
+
+# If we're in test mode, don't do any more work.
+[[ "$test_mode" ]] && exit 0
+
 shift "$(( OPTIND - 1 ))"
 for arg; do
 	header_args+=(--to "$arg")
